apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chess-bot-kaniko-pv
  labels:
    type: local
    app: chess-bot
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/chess_bot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chess-bot-kaniko-pvc
  namespace: cicd
spec:
  selector:
    matchLabels:
      type: local
      app: chess-bot
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
