apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path-pv
  labels:
    type: local
    app: kaniko
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HOST_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: cicd
spec:
  selector:
    matchLabels:
      type: local
      app: kaniko
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
