apiVersion: v1
kind: Secret
metadata:
  name: debian-k3s-tls
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: ${BASE64_ENCODED_CERT_CONTENT}
  tls.key: ${BASE64_ENCODED_KEY_CONTENT}
