apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-${TIMESTAMP}
  namespace: cicd
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=Dockerfile"
          - "--context=/workspace"
          - "--destination=${IMAGE_DESTINATION}"
        volumeMounts:
          - name: local-path-volume
            mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: local-path-volume
          persistentVolumeClaim:
            claimName: local-path-pvc
