apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-tls
  namespace: docker-registry
spec:
  dnsNames:
    - docker-registry.node.external
  secretName: docker-registry-tls
  issuerRef:
    name: k3s-server-ca-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docker-registry-ingress-route
  namespace: docker-registry
spec:
  entryPoints:
    - websecure
  tls:
    secretName: docker-registry-tls
  routes:
    - kind: Rule
      match: Host("docker-registry.node.external")
      services:
        - kind: Service
          port: 5000
          name: docker-registry
