apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  repo: https://helm.twun.io
  chart: docker-registry
  targetNamespace: docker-registry