hull:
  config:
    general:
      rbac: false
      noObjectNamePrefixes: true
  objects:
    serviceaccount:
      default:
        enabled: false
    deployment:
      chess-bot:
        pod:
          containers:
            main:
              image:
                repository: docker-registry:5000/chess-bot
                tag: latest
              env:
                RUST_LOG:
                  value: debug
              ports:
                http:
                  containerPort: 8080
    service:
      chess-bot:
        type: ClusterIP
        ports:
          http:
            port: 8080
            targetPort: 8080

