apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: debian-k3s-tls
  namespace: traefik
spec:
  dnsNames:
    - debian-k3s
    - chess-bot.debian-k3s
    - grafana.debian-k3s
  secretName: debian-k3s-tls
  issuerRef:
    name: k3s-server-ca-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: debian-k3s-tls
