apiVersion: v1
kind: Secret
metadata:
  name: k3s-server-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: ${BASE64_ENCODED_CERT_CONTENT}
  tls.key: ${BASE64_ENCODED_KEY_CONTENT}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: k3s-server-ca-issuer
spec:
  ca:
    secretName: k3s-server-ca-secret
