apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: kube-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: base
  targetNamespace: istio-system
  createNamespace: true
  version: 1.24.0
