apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: linkerd-crds
  namespace: kube-system
spec:
  repo: https://helm.linkerd.io/edge
  chart: linkerd-crds
  version: 2024.11.2
  targetNamespace: linkerd
  createNamespace: true
  valuesContent: |-
    # TODO: CRD collision as per https://github.com/linkerd/linkerd2/issues/12232
    # kubectl delete crd httproutes.policy.linkerd.io
    enableHttpRoutes: false
    enableTcpRoutes: false
    enableTlsRoutes: false
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: linkerd-control-plane
  namespace: kube-system
spec:
  repo: https://helm.linkerd.io/edge
  chart: linkerd-control-plane
  version: 2024.11.2
  targetNamespace: linkerd
  createNamespace: true
  valuesContent: |-
    prometheusUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    podMonitor:
      enabled: true
      controller:
        enabled: true
        namespaceSelector: |
          matchNames:
            - {{ .Release.Namespace }}
            - traefik
            - chess-bot
    identityTrustAnchorsPEM: |
${CA_CERT_PEM}
    identity:
      issuer:
        scheme: linkerd.io/tls
        tls:
          crtPEM: |
${ISSUER_CERT_PEM}
          keyPEM: |
${ISSUER_KEY_PEM}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: linkerd-viz
  namespace: kube-system
spec:
  repo: https://helm.linkerd.io/edge
  chart: linkerd-viz
  version: 2024.11.2
  targetNamespace: linkerd
  createNamespace: true
  valuesContent: |-
    dashboard:
      enforcedHostRegexp: '.*'
    grafana:
      url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
    prometheusUrl: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    prometheus:
      enabled: false
    