apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    loki:
      isDefault: false
      image:
        tag: 2.9.3
