apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tempo
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: tempo
  targetNamespace: monitoring
