apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  targetNamespace: traefik
  createNamespace: true
  version: 33.0.0
  valuesContent: |-
    deployment:
      podAnnotations:
        linkerd.io/inject: enabled
    logs:
      general:
        level: TRACE
      access:
        enabled: true
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        gateway:
          namespacePolicy: All
          listeners:
            web:
              port: 8000
              protocol: HTTP
              namespacePolicy: All
              allowedRoutes:
                namespaces:
                  from: Same
            websecure:
              port: 8443
              protocol: HTTPS
              namespacePolicy: All
              allowedRoutes:
                namespaces:
                  from: Same
              certificateRefs:
                - kind: Secret
                  name: gateway-tls
                  namespace: traefik
