apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  targetNamespace: traefik
  createNamespace: true
  version: 27.0.0
  valuesContent: |-
    deployment:
      podAnnotations:
        linkerd.io/inject: enabled # TODO: enabled or ingress?
